# Generated by Django 3.0.4 on 2020-03-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200330_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the note', max_length=255, null=True),
        ),
    ]
