# Generated by Django 3.0.4 on 2020-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='note_text',
            field=models.TextField(default=' ', help_text='Note'),
            preserve_default=False,
        ),
    ]
