# Generated by Django 3.0.4 on 2020-03-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_location_note_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
    ]
