# Generated by Django 3.0.4 on 2020-03-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200331_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='title',
        ),
    ]
