# Generated by Django 3.0.4 on 2020-04-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200417_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Creator of the note', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Creator of the note', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_locations', to='core.UserProfile'),
        ),
    ]
